-- MySQL Script generated by MySQL Workbench
-- Mon Jun 27 15:25:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petHelio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petHelio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petHelio` DEFAULT CHARACTER SET utf8 ;
USE `petHelio` ;

-- -----------------------------------------------------
-- Table `petHelio`.`TipoAnimal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petHelio`.`TipoAnimal` (
  `idTipoAnimal` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoAnimal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petHelio`.`RacaAnimal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petHelio`.`RacaAnimal` (
  `idRacaAnimal` INT NOT NULL AUTO_INCREMENT,
  `raca` VARCHAR(45) NULL,
  `TipoAnimal_idTipoAnimal` INT NOT NULL,
  PRIMARY KEY (`idRacaAnimal`),
  INDEX `fk_RacaAnimal_TipoAnimal_idx` (`TipoAnimal_idTipoAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_RacaAnimal_TipoAnimal`
    FOREIGN KEY (`TipoAnimal_idTipoAnimal`)
    REFERENCES `petHelio`.`TipoAnimal` (`idTipoAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petHelio`.`DonoAnimal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petHelio`.`DonoAnimal` (
  `idDonoAnimal` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NULL,
  `email` VARCHAR(64) NULL,
  `cpf` BIGINT NULL,
  `telefone` BIGINT NULL,
  `celular` BIGINT NULL,
  `logradouro` VARCHAR(128) NULL,
  `numero` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(128) NULL,
  `estado` CHAR(2) NULL,
  PRIMARY KEY (`idDonoAnimal`),
  UNIQUE INDEX `idDonoAnimal_UNIQUE` (`idDonoAnimal` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petHelio`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petHelio`.`Animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `chipID` VARCHAR(64) NULL,
  `nascimento` DATE NULL,
  `sexo` CHAR NULL,
  `RacaAnimal_idRacaAnimal` INT NOT NULL,
  `DonoAnimal_idDonoAnimal` INT NOT NULL,
  PRIMARY KEY (`idAnimal`),
  UNIQUE INDEX `idAnimal_UNIQUE` (`idAnimal` ASC) VISIBLE,
  INDEX `fk_Animal_RacaAnimal1_idx` (`RacaAnimal_idRacaAnimal` ASC) VISIBLE,
  INDEX `fk_Animal_DonoAnimal1_idx` (`DonoAnimal_idDonoAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_RacaAnimal1`
    FOREIGN KEY (`RacaAnimal_idRacaAnimal`)
    REFERENCES `petHelio`.`RacaAnimal` (`idRacaAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_DonoAnimal1`
    FOREIGN KEY (`DonoAnimal_idDonoAnimal`)
    REFERENCES `petHelio`.`DonoAnimal` (`idDonoAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petHelio`.`Veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petHelio`.`Veterinario` (
  `idVeterinario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NULL,
  `email` VARCHAR(64) NULL,
  `senha` VARCHAR(45) NULL,
  `CRMV` VARCHAR(45) NULL,
  `cpf` BIGINT NULL,
  PRIMARY KEY (`idVeterinario`),
  UNIQUE INDEX `idVeterinario_UNIQUE` (`idVeterinario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petHelio`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petHelio`.`Consulta` (
  `idConsulta` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `hora` TIME NULL,
  `Animal_idAnimal1` INT NOT NULL,
  `Veterinario_idVeterinario` INT NOT NULL,
  PRIMARY KEY (`idConsulta`),
  UNIQUE INDEX `idConsulta_UNIQUE` (`idConsulta` ASC) VISIBLE,
  INDEX `fk_Consulta_Animal2_idx` (`Animal_idAnimal1` ASC) VISIBLE,
  INDEX `fk_Consulta_Veterinario1_idx` (`Veterinario_idVeterinario` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Animal2`
    FOREIGN KEY (`Animal_idAnimal1`)
    REFERENCES `petHelio`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Veterinario1`
    FOREIGN KEY (`Veterinario_idVeterinario`)
    REFERENCES `petHelio`.`Veterinario` (`idVeterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petHelio`.`ANAMNESE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petHelio`.`ANAMNESE` (
  `idANAMNESE` INT NOT NULL AUTO_INCREMENT,
  `peso` FLOAT NULL,
  `pulgas` CHAR NULL,
  `carrapatos` CHAR NULL,
  `motivoVisita` VARCHAR(1024) NULL,
  `observacoes` VARCHAR(1024) NULL,
  `diagnostico` VARCHAR(1024) NULL,
  `Consulta_idConsulta` INT NOT NULL,
  PRIMARY KEY (`idANAMNESE`),
  INDEX `fk_ANAMNESE_Consulta1_idx` (`Consulta_idConsulta` ASC) VISIBLE,
  CONSTRAINT `fk_ANAMNESE_Consulta1`
    FOREIGN KEY (`Consulta_idConsulta`)
    REFERENCES `petHelio`.`Consulta` (`idConsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
